---
- name: Setup Proxy
  hosts: test
  become: true
  vars: 
    squid_port: 3128
    localnet: "192.168.29.0/24"
    pkg: [squid, haproxy]
  tasks:
    - name: Install Squid and HAProxy
      apt: 
        name: "{{ pkg }}"
        state: present
      become: yes

    - name: Squid Proxy configurations
      ansible.builtin.template:
        src: "templates/squid.conf.j2"
        dest: "/etc/squid/conf.d/custom.conf"

#    - name: Check for Data
#      shell: grep -c "b_squid" /etc/haproxy/haproxy.cfg || true
#      register: check_grep

    - name: HAProxy Proxy configurations
      blockinfile:
        path: "/etc/haproxy/haproxy.cfg"
        insertafter: EOF
        block: "{{ lookup('ansible.builtin.file', 'templates/haproxy.cfg') }}"
        state: present
#      when: check_grep.stdout =="0"

    - name: Services Enabling
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop: "{{ pkg }}"

